import { Button, CloseIcon, EffectTag } from 'features/shared';
import type { NewsItem } from 'features/types/types';
import { useEffect } from 'react';

interface NewsModalProps {
	news: NewsItem;
	onClose: () => void;
}

export const NewsModal = ({ news, onClose }: NewsModalProps) => {
	useEffect(() => {
		const originalOverflow = document.body.style.overflow;
		document.body.style.overflow = 'hidden';
		return () => {
			document.body.style.overflow = originalOverflow;
		};
	}, []);

	return (
		<div
			className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
			role="presentation"
			onClick={onClose}
		>
			<div
				role="dialog"
				aria-modal="true"
				aria-label="뉴스 상세 모달"
				className="max-h-[90vh] w-full max-w-[800px] overflow-y-auto rounded-xl bg-white p-6"
				onClick={(event) => event.stopPropagation()}
			>
				<div className="border-b border-gray-200 pb-4">
					<div className="flex items-start justify-between gap-4">
						<div className="flex flex-col gap-1.5">
							<h2 className="text-xl leading-tight font-semibold text-gray-900">
								{news.title}
							</h2>
							<p className="text-sm text-gray-600">
								<span className="font-medium">{news.source}</span>
								<span className="mx-2 text-gray-300">|</span>
								<span className="">{news.publishedAt}</span>
							</p>
						</div>
						<div className="flex items-center">
							<button
								type="button"
								onClick={onClose}
								aria-label="닫기"
								className="cursor-pointer rounded-lg p-2 text-gray-500 transition hover:bg-gray-100 hover:text-gray-700"
							>
								<CloseIcon />
							</button>
						</div>
					</div>
				</div>

				<div className="space-y-6 pt-6">
					<img
						src={news.imageUrl}
						alt={news.title}
						className="h-[420px] w-full rounded-lg object-cover"
					/>

					<section className="space-y-2.5">
						<h3 className="text-base font-semibold text-gray-800">
							Key Takeaways
						</h3>
						<ol className="space-y-2">
							{news.summary.map((line: string, idx: number) => (
								<li key={idx} className="flex items-center gap-2.5">
									<span className="flex h-5 w-5 items-center justify-center rounded-md bg-gray-200 text-xs font-semibold text-gray-700">
										{idx + 1}
									</span>
									<p className="text-base text-gray-800">{line}</p>
								</li>
							))}
						</ol>
					</section>

					<section className="rounded-lg border border-gray-200 bg-gray-50 px-5 py-3">
						<div className="flex items-center gap-2">
							<p className="text-base font-semibold text-gray-800">
								Impact Analysis
							</p>
							<EffectTag effect={news.impact} />
						</div>
						<p className="mt-1 text-base break-keep text-gray-800">
							{news.impactSummary}
						</p>
					</section>

					<section className="rounded-lg border border-blue-100 bg-blue-50 px-5 py-3">
						<p className="text-base font-semibold text-blue-800">
							Next Checkpoint
						</p>
						<p className="mt-1 text-base break-keep text-gray-800">
							{news.nextCheckpoint}
						</p>
					</section>

					<section>
						<p className="text-xs font-normal text-gray-400">
							This summary is generated by AI and should be used for reference
							only. Please review the original article and make investment
							decisions carefully.
						</p>
					</section>

					<div className="grid grid-cols-2 gap-3 border-t border-gray-200 pt-6">
						<a
							href={news.articleUrl}
							target="_blank"
							rel="noreferrer noopener"
							className="cursor-pointer rounded-lg bg-gray-800 px-4.5 py-3 text-center text-base text-white transition-all duration-300 hover:bg-black"
						>
							Go to Article
						</a>
						<Button variant={'gray'} size={'md'} onClick={onClose}>
							Close
						</Button>
					</div>
				</div>
			</div>
		</div>
	);
};
