import { Button, CloseIcon, EffectTag, Portal } from 'features/shared';
import { useToast } from 'features/shared/ui/Toast/useToast';
import type { NewsItem } from 'features/types/types';

interface NewsModalProps {
	news: NewsItem;
	onClose: () => void;
}

export const NewsModal = ({ news, onClose }: NewsModalProps) => {
	const { addToast } = useToast();
	// TODO(a11y): 모달 띄워진 후 키보드 focus 모달 내로 오도록 작업 필요

	return (
		<Portal>
			<div
				className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/55 p-4 backdrop-blur-sm"
				role="presentation"
				onClick={onClose}
			>
				<div
					role="dialog"
					aria-modal="true"
					aria-label="뉴스 상세 모달"
					className="rounded-panel shadow-float max-h-[90vh] w-full max-w-[820px] overflow-y-auto border border-slate-200/80 bg-white/97 p-5 sm:p-6"
					onClick={(event) => event.stopPropagation()}
				>
					<div className="border-b border-slate-200/80 pb-4">
						<div className="flex items-start justify-between gap-4">
							<div className="flex flex-col gap-1.5">
								<h2 className="text-xl leading-tight font-semibold tracking-tight text-slate-900 sm:text-2xl">
									{news.title}
								</h2>
								<p className="text-sm text-slate-600">
									<span className="font-medium text-slate-700">
										{news.source}
									</span>
									<span className="mx-2 text-slate-300">|</span>
									<span className="">{news.publishedAt}</span>
								</p>
							</div>
							<div className="flex items-center">
								<button
									type="button"
									onClick={onClose}
									aria-label="닫기"
									className="cursor-pointer rounded-xl border border-slate-200/80 bg-white p-2 text-slate-500 transition-all hover:-translate-y-0.5 hover:bg-slate-50 hover:text-slate-700"
								>
									<CloseIcon />
								</button>
							</div>
						</div>
					</div>

					<div className="space-y-6 pt-6">
						<img
							src={news.imageUrl}
							alt={news.title}
							className="h-[320px] w-full rounded-2xl object-cover"
						/>

						<section className="space-y-2.5">
							<h3 className="text-base font-semibold text-slate-800">
								Key Takeaways
							</h3>
							<ol className="space-y-2">
								{news.summary.map((line: string, idx: number) => (
									<li key={idx} className="flex items-center gap-2.5">
										<span className="flex h-5 w-5 items-center justify-center rounded-md bg-slate-200 text-xs font-semibold text-slate-700">
											{idx + 1}
										</span>
										<p className="text-base text-slate-800">{line}</p>
									</li>
								))}
							</ol>
						</section>

						<section className="rounded-2xl border border-slate-200/80 bg-slate-50/75 px-5 py-3.5">
							<div className="flex items-center gap-2">
								<p className="text-base font-semibold text-slate-800">
									Impact Analysis
								</p>
								<EffectTag effect={news.impact} />
							</div>
							<p className="mt-1 text-base break-keep text-slate-800">
								{news.impactSummary}
							</p>
						</section>

						<section className="border-primary/20 bg-primary/8 rounded-2xl border px-5 py-3.5">
							<p className="text-primary-dark text-base font-semibold">
								Next Checkpoint
							</p>
							<p className="mt-1 text-base break-keep text-slate-800">
								{news.nextCheckpoint}
							</p>
						</section>

						<section>
							<p className="text-xs font-normal text-slate-400">
								This summary is generated by AI and should be used for reference
								only. Please review the original article and make investment
								decisions carefully.
							</p>
						</section>

						<div className="grid grid-cols-2 gap-3 border-t border-slate-200/80 pt-6">
							<Button
								variant={'black'}
								size={'md'}
								onClick={() => addToast('관심 뉴스에 저장되었습니다.')}
							>
								+ 관심 뉴스 저장
							</Button>
							{/* <a
								href={news.articleUrl}
								target="_blank"
								rel="noreferrer noopener"
								className="shadow-soft cursor-pointer rounded-xl border border-slate-900 bg-slate-900 px-4.5 py-3 text-center text-base text-white transition-all duration-300 hover:-translate-y-0.5 hover:bg-black"
							>
								Go to Article
							</a> */}
							<Button variant={'gray'} size={'md'} onClick={onClose}>
								Close
							</Button>
						</div>
					</div>
				</div>
			</div>
		</Portal>
	);
};
